# Generated by Django 2.1.7 on 2019-02-20 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chasis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodArticulo', models.CharField(max_length=30)),
                ('CodOT', models.CharField(max_length=30)),
                ('CodSv', models.CharField(max_length=15)),
                ('Usuario', models.CharField(max_length=50)),
                ('FechaCreaChasis', models.DateField(verbose_name='Fecha Creado')),
                ('Descripcion', models.CharField(max_length=200)),
            ],
        ),
    ]
