# Generated by Django 2.1.7 on 2019-02-20 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_chasis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chasis',
        ),
    ]
