# Generated by Django 2.1.7 on 2019-02-20 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_cl_chasis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cl_chasis',
            options={'managed': False},
        ),
    ]
