# Generated by Django 2.1.7 on 2019-02-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20190219_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_text2',
            field=models.CharField(default='-', max_length=200),
            preserve_default=False,
        ),
    ]
