# Generated by Django 2.1.7 on 2019-02-20 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_chasis'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chasis',
            table='CHASIS',
        ),
        migrations.AlterModelTable(
            name='cl_chasis',
            table='CL_CHASIS',
        ),
    ]
