# Generated by Django 2.1.7 on 2019-02-20 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20190219_2235'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chasis',
            table='CL_CHASIS',
        ),
    ]
